package com.cubic.jpa.entity;

public interface QueryConstant {
	String CUSTOMER_SELECT_ALL = "CUSTOMER_SELECT_ALL";
	String CUSTOMER_SEARCH = "CUSTOMER_SELECT";
	String CUSTOMER_COUNT = "CUSTOMER_COUNT";
	String N_CUSTOMER_SELECT_ALL = "N_CUSTOMER_SELECT_ALL";
	String N_CUSTOMER_SEARCH = "N_CUSTOMER_SELECT";
	String N_CUSTOMER_COUNT = "N_CUSTOMER_COUNT";

}
