DROP TABLE PRESCRIBER;
CREATE TABLE PRESCRIBER 
(	
	ID NUMBER(38,0) NOT NULL, 
	FIRSTNAME VARCHAR2(20) NOT NULL, 
	LASTNAME VARCHAR2(20) NOT NULL, 
	PHONENUMBER NUMBER(11) NOT NULL, 
	FAXNUMBER NUMBER(11), 
	EMAILI VARCHAR2(20), 
	DEANUMBER VARCHAR2(9) NOT NULL, 
	SPECIALIZATION VARCHAR2(20) NOT NULL, 
	CREATEDDATE DATE NOT NULL, 
	MODIFIEDDATE DATE, 
	STATUS VARCHAR2(8), 
	DESCRIPTION CLOB, 
	DOB DATE, 
	GENDER VARCHAR2(6) NOT NULL, 
	 CONSTRAINT PRESCRIBER_PK PRIMARY KEY 
	 (
	 ID
	 )
	 ENABLE
   );
   COMMIT;
CREATE OR REPLACE TRIGGER CREATED_DATE BEFORE INSERT ON PRESCRIBER 
FOR EACH ROW
BEGIN
 :NEW.CREATEDDATE := SYSDATE;
END;
CREATE OR REPLACE TRIGGER MODIFIED_DATE BEFORE UPDATE ON PRESCRIBER 
FOR EACH ROW
BEGIN
 :NEW.MODIFIEDDATE := SYSDATE;
END;
